
development:
  adapter: postgresql
  database: mayacom_development
  host: localhost
  username: postgres
  password: password

test:
  adapter: postgresql
  database: mayacom_test
  host: localhost
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: mayacom_production
  pool: 5
  username: mayacom
  password:
