# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')

AccessType.create!(name: "Adaptadores")
AccessType.create!(name: "Auriculares")
AccessType.create!(name: "Baterias ")
AccessType.create!(name: "Bluetooth")
AccessType.create!(name: "Bumpers")
AccessType.create!(name: "Cables")
AccessType.create!(name: "Carcasas")
AccessType.create!(name: "Cargadores")
AccessType.create!(name: "Clip")
AccessType.create!(name: "Estuches")
AccessType.create!(name: "Films")
AccessType.create!(name: "Impresoras")
AccessType.create!(name: "Lápiz")
AccessType.create!(name: "Manos Libres")
AccessType.create!(name: "Memorias")
AccessType.create!(name: "Parlantes")
AccessType.create!(name: "Protectores")
AccessType.create!(name: "Siliconas")
AccessType.create!(name: "Soportes")

Brand.create!(name:"Acer")
Brand.create!(name:"Alcatel")
Brand.create!(name:"Apple")
Brand.create!(name:"BlackBerry")
Brand.create!(name:"Doogee")
Brand.create!(name:"Huawei")
Brand.create!(name:"LG")
Brand.create!(name:"Motorola")
Brand.create!(name:"Nokia")
Brand.create!(name:"Samsung")
Brand.create!(name:"Sony")
Brand.create!(name:"Unicell")

Technology.create!(name: "GSM")
Technology.create!(name: "3G")
Technology.create!(name: "LTE")